// src/data/captchaData.js

export const captchaData = [
    { img: 'captchas/captcha1.png', answer: "c2['sd" },
    { img: 'captchas/captcha2.png', answer: "fe'8:3" },
    { img: 'captchas/captcha3.png', answer: "\g42`" },
    { img: 'captchas/captcha4.png', answer: "/2)78G" },
  ];
  
  export const voiceCaptchaData = [
    { answer: "pretty banana" },
    { answer: "brave horse" },
    { answer: "yellow house" },
    { answer: "red sun" },
    { answer: "blue sky" },
    { answer: "happy cat" },
    { answer: "green tree" },
    { answer: "fast car" },
    { answer: "bright star" },
    { answer: "loud music" },
    { answer: "cold ice" },
    { answer: "warm fire" },
    { answer: "soft pillow" },
    { answer: "sharp knife" },
    { answer: "sweet candy" },
    { answer: "large ocean" },
    { answer: "small mouse" },
    { answer: "strong wind" },
    { answer: "smooth stone" },
    { answer: "tall building" },
    { answer: "long road" },
    { answer: "deep lake" },
    { answer: "big mountain" },
    { answer: "bright moon" },
    { answer: "light rain" },
    { answer: "hot sun" },
    { answer: "dark night" },
    { answer: "fresh bread" },
    { answer: "strong coffee" },
    { answer: "soft blanket" },
    { answer: "clear water" },
    { answer: "quick rabbit" },
    { answer: "high cloud" },
    { answer: "cool breeze" },
    { answer: "silent room" },
    { answer: "small flower" },
    { answer: "bright light" },
    { answer: "gentle breeze" },
    { answer: "noisy street" },
    { answer: "sweet apple" },
    { answer: "happy dog" },
    { answer: "tasty pizza" },
    { answer: "fluffy bunny" },
    { answer: "large park" },
    { answer: "quiet library" },
    { answer: "sweet chocolate" },
    { answer: "calm sea" },
    { answer: "bouncy ball" },
    { answer: "crisp apple" },
    { answer: "lively market" },
    { answer: "shiny car" },
    { answer: "fast runner" },
    { answer: "soft kitten" },
    { answer: "cold drink" },
    { answer: "clean room" },
    { answer: "bright sun" },
    { answer: "fresh fruit" },
    { answer: "newspaper" },
  ];
  